/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEIP2981,
  IEIP2981Interface,
} from "../../../contracts/nft/IEIP2981";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_salePrice",
        type: "uint256",
      },
    ],
    name: "royaltyInfo",
    outputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "royaltyAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEIP2981__factory {
  static readonly abi = _abi;
  static createInterface(): IEIP2981Interface {
    return new utils.Interface(_abi) as IEIP2981Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEIP2981 {
    return new Contract(address, _abi, signerOrProvider) as IEIP2981;
  }
}
